### PR TITLE
Added custom abilitys

### PR DESCRIPTION
**Pull request by DevBlokJochem**
I've added the speed, lightning and heal ability. They will drop when you kill a  mob.

### CODE REVIEW

**Review by TheMode — CHANGES_REQUESTED** [review]
Additionally to these issues:
- You must apply formatting (see the `editorconfig` file)
- All your changes only involve the `arena.mob` arena. Only this package should therefore be affected.
- The checks seem to be pretty weak (rely on material, entity type) and are hardcoded

**Comment by DevBlokJochem** [comment]
> Additionally to these issues:
> - You must apply formatting (see the `editorconfig` file)
> - All your changes only involve the `arena.mob` arena. Only this package should therefore be affected.
> - The checks seem to be pretty weak (rely on material, entity type) and are hardcoded

I think that I've fixed everything.

**Comment by DevBlokJochem** [comment]
someone else has made a shop for healing/abilitys so Im going to close this pull request.

**Comment by kiip1** [comment]
> someone else has made a shop for healing/abilitys so Im going to close this pull request.

My PR was for a shop, your abilities could still work. I don't mind healing being removed from the shop and being obtainable as powerups instead.

**Pull request closed without merging**
